/*
 * generated by Xtext
 */
package com.isax.validation.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends com.isax.validation.dsl.AbstractDslRuntimeModule {

}
