/*
* generated by Xtext
*/
package com.isax.validation.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.isax.validation.dsl.ui.internal.DslActivator.getInstance().getInjector("com.isax.validation.dsl.Dsl");
	}
	
}
