/*
 * generated by Xtext
 */
package com.isax.validation.dsl;

import org.eclipse.xtext.common.types.xtext.AbstractTypeScopeProvider;
import org.eclipse.xtext.scoping.IScopeProvider;

import com.isax.validation.dsl.scoping.DslContextScopeProvider;
import com.isax.validation.dsl.scoping.DslScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends com.isax.validation.dsl.AbstractDslRuntimeModule {
	
//	@Override
//	public Class<? extends IGenerator> bindIGenerator() {
//		return DslGenerator.class;
//	}
	
//	@Override
//	public Class<? extends IScopeProvider> bindIScopeProvider() {
//		return DslScopeProvider.class;
//	}
	
//	@Override
//	public Class<? extends AbstractTypeScopeProvider> bindAbstractTypeScopeProvider() {
//		return DslContextScopeProvider.class;
//	}
	
	
}
