/*
 * generated by Xtext
 */
package com.isax.validation.dsl;

import org.eclipse.xtext.linking.LinkingScopeProviderBinding;
import org.eclipse.xtext.scoping.IScopeProvider;

import com.google.inject.Binder;
import com.isax.validation.dsl.scoping.DslScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class DslRuntimeModule extends com.isax.validation.dsl.AbstractDslRuntimeModule {

	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return DslScopeProvider.class;
	}

	@Override
	public void configureLinkingIScopeProvider(Binder binder) {
		binder.bind(IScopeProvider.class).annotatedWith(LinkingScopeProviderBinding.class).to(DslScopeProvider.class);
	}

}
