/**
 * generated by Xtext
 */
package com.isax.validation.dsl.ui.contentassist;

import com.isax.validation.dsl.ui.contentassist.AbstractDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DslProposalProvider extends AbstractDslProposalProvider {
}
